version: '2'
volumes:
    db-data:
    config-data:
services:
  opendatacam:
    restart: always
    build: .
    privileged: true
    volumes:
      - 'db-data:/data/db'
      - 'config-data:/data/odc'
    ports:
      - "8080:8080"
      - "8070:8070"
      - "8090:8090"
  mongo:
    image: mongo:4.4.8
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - 'db-data:/data/db'
