version: '2'
volumes:
    home-data:
services:
  opendatacam:
    restart: always
    build: .
    privileged: true
    volumes:
      - 'home-data:/data/db'
    ports:
      - "8080:8080"
      - "8070:8070"
      - "8090:8090"
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - 'home-data:/data/db'
